<../../mkconfig

DIRS=\
	convcs\
	crypt\
	ecmascript\
	encoding\
	ida\
	print\
	spki\
	strokes\
	styxconv\
	usb\
	w3c\

TARG=\
	arg.dis\
	asn1.dis\
	attrdb.dis\
	attrhash.dis\
	auth.dis\
	auth9.dis\
	bloomfilter.dis\
	bufio.dis\
	cfg.dis\
	cfgfile.dis\
	chanfill.dis\
	complete.dis\
	crc.dis\
	csv.dis\
	daytime.dis\
	db.dis\
	dbm.dis\
	dbsrv.dis\
	debug.dis\
	deflate.dis\
	devpointer.dis\
	dhcpclient.dis\
	dialog.dis\
	dict.dis\
	dis.dis\
	diskblocks.dis\
	disks.dis\
	dividers.dis\
	env.dis\
	ether.dis\
	exception.dis\
	factotum.dis\
	filepat.dis\
	format.dis\
	fsfilter.dis\
	fslib.dis\
	fsproto.dis\
	gamer.dis\
	hash.dis\
	html.dis\
	imageremap.dis\
	inflate.dis\
	ip.dis\
	ipattr.dis\
	ir.dis\
	irsage.dis\
	irsim.dis\
	itslib.dis\
	json.dis\
	keyset.dis\
	libc.dis\
	libc0.dis\
	lists.dis\
	lock.dis\
	login.dis\
	man.dis\
	mpeg.dis\
	msgio.dis\
	nametree.dis\
	names.dis\
	newns.dis\
	palm.dis\
	palmdb.dis\
	palmfile.dis\
	parseman.dis\
	plumbmsg.dis\
	plumbing.dis\
	pop3.dis\
	popup.dis\
	powerman.dis\
	profile.dis\
	pslib.dis\
	quicktime.dis\
	rand.dis\
	random.dis\
	readdir.dis\
	readgif.dis\
	readjpg.dis\
	readpicfile.dis\
	readpng.dis\
	readxbitmap.dis\
	regex.dis\
	regexutils.dis\
	registries.dis\
	rfc822.dis\
	riff.dis\
	scoretable.dis\
	scsiio.dis\
	secstore.dis\
	selectfile.dis\
	sets.dis\
	sets32.dis\
	sexprs.dis\
	slip.dis\
	smtp.dis\
	sort.dis\
	ssl.dis\
	string.dis\
	strinttab.dis\
	styx.dis\
	styxflush.dis\
	styxlib.dis\
	styxpersist.dis\
	styxservers.dis\
	tables.dis\
	tabs.dis\
	tftp.dis\
	timers.dis\
	tcl_utils.dis\
#	tcl_tk.dis\
	tcl_symhash.dis\
	tcl_string.dis\
	tcl_strhash.dis\
	tcl_stack.dis\
	tcl_modhash.dis\
	tcl_list.dis\
	tcl_io.dis\
	tcl_inthash.dis\
	tcl_core.dis\
	tcl_calc.dis\
	tkclient.dis\
	titlebar.dis\
	translate.dis\
	ubfa.dis\
	url.dis\
	vac.dis\
	venti.dis\
	virgil.dis\
	volume.dis\
	wait.dis\
	watchvars.dis\
	winplace.dis\
	wmclient.dis\
	wmlib.dis\
	wmsrv.dis\
	workdir.dis\
	writegif.dis\
	xml.dis\

MODULES=

SYSMODULES= \
	bufio.m\
	cci.m\
	daytime.m\
	db.m\
	debug.m\
	devpointer.m\
	dict.m\
	draw.m\
	env.m\
	exception.m\
	filepat.m\
	filter.m\
	fslib.m\
	hash.m\
	html.m\
	imagefile.m\
	inflate.m\
	ir.m\
	keyring.m\
	lock.m\
	man.m\
	mpeg.m\
	newns.m\
	palmfile.m\
	plumbmsg.m\
	powerman.m\
	prefab.m\
	pslib.m\
	quicktime.m\
	rand.m\
	readdir.m\
	regex.m\
	riff.m\
	scoretable.m\
	security.m\
	sh.m\
	smtp.m\
	srv.m\
	string.m\
	styx.m\
	styxservers.m\
	sys.m\
	tables.m\
	url.m\
	venti.m\
	volume.m\
	watchvars.m\
	wmlib.m\

DISBIN=$ROOT/dis/lib

<$ROOT/mkfiles/mkdis
<$ROOT/mkfiles/mksubdirs

plumbing.dis:N: plumbing.m
plumber.dis:N: plumbing.m

ip.dis: $ROOT/module/ip.m
ether.dis:	$ROOT/module/ether.m
attrdb.dis attrhash.dis:	$ROOT/module/attrdb.m
ipattr.dis:	$ROOT/module/attrdb.m $ROOT/module/ip.m $ROOT/module/ipattr.m
tftp.dis:	$ROOT/module/tftp.m
registries.dis:	$ROOT/module/registries.m
keyset.dis:	$ROOT/module/keyset.m
auth9.dis: $ROOT/module/auth9.m
factotum.dis:	$ROOT/module/factotum.m
sexprs.dis:	$ROOT/module/sexprs.m
dbm.dis: $ROOT/module/dbm.m
names.dis: $ROOT/module/names.m
disks.dis: $ROOT/module/disks.m
scsiio.dis:	$ROOT/module/scsiio.m
dhcpclient.dis:	$ROOT/module/dhcp.m
ubfa.dis: $ROOT/module/ubfa.m
secstore.dis:	$ROOT/module/secstore.m
ida.dis:	$ROOT/module/ida.m
rfc822.dis:	$ROOT/module/rfc822.m
csv.dis: $ROOT/module/csv.m
json.dis: $ROOT/module/json.m
lists.dis:	$ROOT/module/lists.m
vac.dis:	$ROOT/module/vac.m $ROOT/module/venti.m
dial.dis:	$ROOT/module/dial.m
styxflush.dis:	$ROOT/module/styxflush.m
msgio.dis:	$ROOT/module/msgio.m
