<../../mkconfig

TARG=srclist

OFILES=	srclist.$O\
	$TARGMODEL.$O\

HFILES=\
	a.out.h\
	bio.h\
	mach.h\

LIBS=mach bio 9	# order matters.

CFLAGS=$CFLAGS -I../include

BIN=$ROOT/$OBJDIR/bin

<$ROOT/mkfiles/mkone-$SHELLTYPE
