<../../mkconfig

MODDIR=$ROOT/module
LIMBOFLAGS=-I$MODDIR -I.

DISBIN=$ROOT/dis/veltro

MAIN=\
    agentlib.dis\
    veltro.dis\
    repl.dis\
    tools9p.dis\
    nsconstruct.dis\
    cowfs.dis\
    subagent.dis\
    mc9p.dis\
    speech9p.dis\
    msg9p.dis\
    msgwatch.dis\

SOURCES=\
    sources/email.dis\

TOOLS=\
    tools/read.dis\
    tools/list.dis\
    tools/find.dis\
    tools/search.dis\
    tools/write.dis\
    tools/edit.dis\
    tools/exec.dis\
	tools/launch.dis\
    tools/spawn.dis\
    tools/safeexec.dis\
    tools/xenith.dis\
    tools/editor.dis\
    tools/shell.dis\
    tools/present.dis\
    tools/diff.dis\
    tools/json.dis\
    tools/webfetch.dis\
    tools/git.dis\
    tools/grep.dis\
    tools/memory.dis\
    tools/todo.dis\
    tools/say.dis\
    tools/hear.dis\
    tools/websearch.dis\
    tools/mail.dis\
    tools/browse.dis\
    tools/charon.dis\
    tools/gpu.dis\
    tools/vision.dis\
    tools/fractal.dis\
    tools/task.dis\
    tools/gap.dis\
    tools/plan.dis\
    tools/keyring.dis\

all:V: $MAIN $TOOLS $SOURCES

# Main programs
agentlib.dis: agentlib.b agentlib.m
	limbo $LIMBOFLAGS -gw agentlib.b

veltro.dis: veltro.b agentlib.m tool.m nsconstruct.m
	limbo $LIMBOFLAGS -gw veltro.b

tools9p.dis: tools9p.b tool.m
	limbo $LIMBOFLAGS -gw tools9p.b

nsconstruct.dis: nsconstruct.b nsconstruct.m
	limbo $LIMBOFLAGS -gw nsconstruct.b

cowfs.dis: cowfs.b
	limbo $LIMBOFLAGS -gw cowfs.b

subagent.dis: subagent.b subagent.m tool.m
	limbo $LIMBOFLAGS -gw subagent.b

repl.dis: repl.b agentlib.m
	limbo $LIMBOFLAGS -gw repl.b

mc9p.dis: mc9p.b
	limbo $LIMBOFLAGS -gw mc9p.b

speech9p.dis: speech9p.b
	limbo $LIMBOFLAGS -gw speech9p.b

msg9p.dis: msg9p.b
	limbo $LIMBOFLAGS -gw msg9p.b

msgwatch.dis: msgwatch.b agentlib.m
	limbo $LIMBOFLAGS -gw msgwatch.b

# Sources
sources/email.dis: sources/email.b
	limbo $LIMBOFLAGS -gw -o sources/email.dis sources/email.b

# Tools
tools/read.dis: tools/read.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/read.dis tools/read.b

tools/list.dis: tools/list.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/list.dis tools/list.b

tools/find.dis: tools/find.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/find.dis tools/find.b

tools/search.dis: tools/search.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/search.dis tools/search.b

tools/write.dis: tools/write.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/write.dis tools/write.b

tools/edit.dis: tools/edit.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/edit.dis tools/edit.b

tools/exec.dis: tools/exec.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/exec.dis tools/exec.b

tools/launch.dis: tools/launch.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/launch.dis tools/launch.b

tools/spawn.dis: tools/spawn.b tool.m nsconstruct.m subagent.m
	limbo $LIMBOFLAGS -gw -o tools/spawn.dis tools/spawn.b

tools/safeexec.dis: tools/safeexec.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/safeexec.dis tools/safeexec.b

tools/xenith.dis: tools/xenith.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/xenith.dis tools/xenith.b

tools/editor.dis: tools/editor.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/editor.dis tools/editor.b

tools/shell.dis: tools/shell.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/shell.dis tools/shell.b

tools/present.dis: tools/present.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/present.dis tools/present.b

# New tools (Phase 1c)
tools/diff.dis: tools/diff.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/diff.dis tools/diff.b

tools/json.dis: tools/json.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/json.dis tools/json.b

tools/webfetch.dis: tools/webfetch.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/webfetch.dis tools/webfetch.b

tools/git.dis: tools/git.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/git.dis tools/git.b

tools/grep.dis: tools/grep.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/grep.dis tools/grep.b

tools/memory.dis: tools/memory.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/memory.dis tools/memory.b

tools/todo.dis: tools/todo.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/todo.dis tools/todo.b

# Speech tools
tools/say.dis: tools/say.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/say.dis tools/say.b

tools/hear.dis: tools/hear.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/hear.dis tools/hear.b

tools/websearch.dis: tools/websearch.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/websearch.dis tools/websearch.b

# Mail tool
tools/mail.dis: tools/mail.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/mail.dis tools/mail.b

# Browse tool
tools/browse.dis: tools/browse.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/browse.dis tools/browse.b

# Charon browser tool
tools/charon.dis: tools/charon.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/charon.dis tools/charon.b

# GPU tool
tools/gpu.dis: tools/gpu.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/gpu.dis tools/gpu.b

# Vision tool
tools/vision.dis: tools/vision.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/vision.dis tools/vision.b

# Fractal tool
tools/fractal.dis: tools/fractal.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/fractal.dis tools/fractal.b

# Task delegation tool
tools/task.dis: tools/task.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/task.dis tools/task.b

# Gap tool
tools/gap.dis: tools/gap.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/gap.dis tools/gap.b

# Plan tool
tools/plan.dis: tools/plan.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/plan.dis tools/plan.b

# Keyring tool (credential management)
tools/keyring.dis: tools/keyring.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/keyring.dis tools/keyring.b

install:V: all
	mkdir -p $DISBIN $DISBIN/tools $DISBIN/sources
	cp agentlib.dis veltro.dis repl.dis tools9p.dis nsconstruct.dis cowfs.dis subagent.dis mc9p.dis speech9p.dis msg9p.dis msgwatch.dis $DISBIN/
	cp tools/*.dis $DISBIN/tools/
	cp sources/*.dis $DISBIN/sources/

clean:V:
	rm -f *.dis *.sbl tools/*.dis tools/*.sbl sources/*.dis sources/*.sbl

nuke:V: clean
	rm -rf $DISBIN
