<../../mkconfig

MODDIR=$ROOT/module
LIMBOFLAGS=-I$MODDIR -I.

DISBIN=$ROOT/dis/veltro

MAIN=\
    agentlib.dis\
    veltro.dis\
    repl.dis\
    tools9p.dis\
    nsconstruct.dis\
    subagent.dis\
    mc9p.dis\
    speech9p.dis\

TOOLS=\
    tools/read.dis\
    tools/list.dis\
    tools/find.dis\
    tools/search.dis\
    tools/write.dis\
    tools/edit.dis\
    tools/exec.dis\
    tools/spawn.dis\
    tools/safeexec.dis\
    tools/xenith.dis\
    tools/present.dis\
    tools/diff.dis\
    tools/json.dis\
    tools/ask.dis\
    tools/http.dis\
    tools/git.dis\
    tools/grep.dis\
    tools/memory.dis\
    tools/todo.dis\
    tools/say.dis\
    tools/hear.dis\
    tools/websearch.dis\
    tools/mail.dis\
    tools/browse.dis\
    tools/gpu.dis\

all:V: $MAIN $TOOLS

# Main programs
agentlib.dis: agentlib.b agentlib.m
	limbo $LIMBOFLAGS -gw agentlib.b

veltro.dis: veltro.b agentlib.m tool.m nsconstruct.m
	limbo $LIMBOFLAGS -gw veltro.b

tools9p.dis: tools9p.b tool.m
	limbo $LIMBOFLAGS -gw tools9p.b

nsconstruct.dis: nsconstruct.b nsconstruct.m
	limbo $LIMBOFLAGS -gw nsconstruct.b

subagent.dis: subagent.b subagent.m tool.m
	limbo $LIMBOFLAGS -gw subagent.b

repl.dis: repl.b agentlib.m
	limbo $LIMBOFLAGS -gw repl.b

mc9p.dis: mc9p.b
	limbo $LIMBOFLAGS -gw mc9p.b

speech9p.dis: speech9p.b
	limbo $LIMBOFLAGS -gw speech9p.b

# Tools
tools/read.dis: tools/read.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/read.dis tools/read.b

tools/list.dis: tools/list.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/list.dis tools/list.b

tools/find.dis: tools/find.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/find.dis tools/find.b

tools/search.dis: tools/search.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/search.dis tools/search.b

tools/write.dis: tools/write.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/write.dis tools/write.b

tools/edit.dis: tools/edit.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/edit.dis tools/edit.b

tools/exec.dis: tools/exec.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/exec.dis tools/exec.b

tools/spawn.dis: tools/spawn.b tool.m nsconstruct.m subagent.m
	limbo $LIMBOFLAGS -gw -o tools/spawn.dis tools/spawn.b

tools/safeexec.dis: tools/safeexec.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/safeexec.dis tools/safeexec.b

tools/xenith.dis: tools/xenith.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/xenith.dis tools/xenith.b

tools/present.dis: tools/present.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/present.dis tools/present.b

# New tools (Phase 1c)
tools/diff.dis: tools/diff.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/diff.dis tools/diff.b

tools/json.dis: tools/json.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/json.dis tools/json.b

tools/ask.dis: tools/ask.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/ask.dis tools/ask.b

tools/http.dis: tools/http.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/http.dis tools/http.b

tools/git.dis: tools/git.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/git.dis tools/git.b

tools/grep.dis: tools/grep.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/grep.dis tools/grep.b

tools/memory.dis: tools/memory.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/memory.dis tools/memory.b

tools/todo.dis: tools/todo.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/todo.dis tools/todo.b

# Speech tools
tools/say.dis: tools/say.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/say.dis tools/say.b

tools/hear.dis: tools/hear.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/hear.dis tools/hear.b

tools/websearch.dis: tools/websearch.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/websearch.dis tools/websearch.b

# Mail tool
tools/mail.dis: tools/mail.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/mail.dis tools/mail.b

# Browse tool
tools/browse.dis: tools/browse.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/browse.dis tools/browse.b

# GPU tool
tools/gpu.dis: tools/gpu.b tool.m
	limbo $LIMBOFLAGS -gw -o tools/gpu.dis tools/gpu.b

install:V: all
	mkdir -p $DISBIN $DISBIN/tools
	cp agentlib.dis veltro.dis repl.dis tools9p.dis nsconstruct.dis subagent.dis mc9p.dis speech9p.dis $DISBIN/
	cp tools/*.dis $DISBIN/tools/

clean:V:
	rm -f *.dis *.sbl tools/*.dis tools/*.sbl

nuke:V: clean
	rm -rf $DISBIN
