<$ROOT/mkconfig

DIRS=\

TARG=\
	clock.dis\
	colors.dis\
	lens.dis\
	luciedit.dis\
	mand.dis\
	lucishell.dis\
	view.dis\
	wm.dis\

MODULES=\

SYSMODULES=\
	arg.m\
	bufio.m\
	daytime.m\
	draw.m\
	imagefile.m\
	keyboard.m\
	lucitheme.m\
	math.m\
	menu.m\
	menuhit.m\
	plumbmsg.m\
	sh.m\
	string.m\
	styx.m\
	styxservers.m\
	sys.m\
	winplace.m\
	wmclient.m\
	wmsrv.m\

DISBIN=$ROOT/dis/wm

<$ROOT/mkfiles/mkdis
<$ROOT/mkfiles/mksubdirs
