<../mkconfig

TARG=asm
OFILES=\
	lex.$O\
	assem.$O\
	y.tab.$O

YFILES=	asm.y

HFILES=\
	asm.h\
	$ROOT/libinterp/tab.h\
	$ROOT/include/isa.h\
	y.tab.h

LIBS=bio 9

BIN=$ROOT/$OBJDIR/bin

<$ROOT/mkfiles/mkone-$SHELLTYPE
