<$ROOT/mkconfig

DIRS=\
	testing\

TARG=\
	9p_export_test.dis\
	agentlib_test.dis\
	agent_test.dis\
	tooluse_test.dis\
	asyncio_test.dis\
	cowfs_test.dis\
	crypto_test.dis\
	edit_test.dis\
	example_test.dis\
	font_format_test.dis\
	git_test.dis\
	goroutine_leak_test.dis\
	gpu_test.dis\
	hello_test.dis\
	imgload_test.dis\
	imap_test.dis\
	jit_test.dis\
	lucifer_flicker_test.dis\
	lucitheme_test.dis\
	luciuisrv_test.dis\
	outlinefont_test.dis\
	pdf_conformance_test.dis\
	pdf_test.dis\
	render_registry_test.dis\
	runner.dis\
	sdl3_test.dis\
	spawn_test.dis\
	ssl_transport_test.dis\
	stderr_test.dis\
	tcp_test.dis\
	tempfile_test.dis\
	tls_crypto_test.dis\
	tls_live_test.dis\
	tls_protocol_test.dis\
	webclient_test.dis\
	veltro_concurrent_test.dis\
	veltro_security_test.dis\
	veltro_test.dis\
	veltro_tools_test.dis\
	pathmanage_test.dis\
	tools9p_test.dis\
	pres_launch_test.dis\
	sha3_test.dis\
	mlkem_test.dis\
	mldsa_test.dis\
	slhdsa_test.dis\
	tls_pq_test.dis\
	x509_test.dis\
	xenith_concurrency_test.dis\
	xenith_exit_test.dis\

MODULES=

SYSMODULES=\
	arg.m\
	cowfs.m\
	dial.m\
	factotum.m\
	imap.m\
	asn1.m\
	bufio.m\
	daytime.m\
	draw.m\
	git.m\
	gpu.m\
	keyring.m\
	math.m\
	nsconstruct.m\
	outlinefont.m\
	pdf.m\
	pkcs.m\
	readdir.m\
	renderer.m\
	security.m\
	sh.m\
	string.m\
	sys.m\
	testing.m\
	tls.m\
	webclient.m\
	x509.m\

DISBIN=$ROOT/dis/tests

<$ROOT/mkfiles/mkdis
<$ROOT/mkfiles/mksubdirs

# agentlib_test needs -I for appl/veltro/agentlib.m
agentlib_test.dis: agentlib_test.b $ROOT/appl/veltro/agentlib.m
	limbo -I$ROOT/module -I$ROOT/appl/veltro -gw agentlib_test.b

# tooluse_test needs -I for appl/veltro/agentlib.m
tooluse_test.dis: tooluse_test.b $ROOT/appl/veltro/agentlib.m
	limbo -I$ROOT/module -I$ROOT/appl/veltro -gw tooluse_test.b

# pres_launch_test needs -I for appl/veltro/nsconstruct.m
pres_launch_test.dis: pres_launch_test.b $ROOT/appl/veltro/nsconstruct.m
	limbo -I$ROOT/module -I$ROOT/appl/veltro -gw pres_launch_test.b

# render_registry_test needs -I for appl/xenith/render.m
render_registry_test.dis: render_registry_test.b $ROOT/appl/xenith/render.m
	limbo -I$ROOT/module -I$ROOT/appl/xenith -gw render_registry_test.b
