<../mkconfig

LIB=libprefab.a

OFILES=\
	box.$O\
	compound.$O\
	element.$O\
	elistelement.$O\
	iconbox.$O\
	iconelement.$O\
	textbox.$O\
	textelement.$O\

HFILES=\
	$ROOT/include/draw.h\
	$ROOT/include/prefab.h\

<$ROOT/mkfiles/mksyslib-$SHELLTYPE

$OFILES:	$ROOT/module/prefab.m
