<../../mkconfig

TARG=5l

OFILES=\
	asm.$O\
	list.$O\
	noop.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	enam.$O\
	$TARGMODEL.$O\
	thumb.$O\

HFILES=\
	l.h\
	../5c/5.out.h\
	../include/ar.h\

LIBS=bio 9			# order is important

CFLAGS=$CFLAGS -I../include -I.

BIN=$ROOT/$OBJDIR/bin

<$ROOT/mkfiles/mkone-$SHELLTYPE

enam.$O:	../5c/enam.c
	$CC $CFLAGS ../5c/enam.c

$TARGMODEL.$O:	../ld/$TARGMODEL.c
	$CC $CFLAGS ../ld/$TARGMODEL.c
