<../fonts.pal

tk.ps:D:	tk.ms f1.ps f2.ps mkfile
	{echo $FONTS; cat tk.ms} | tbl | troff -mpm -mpictures | lp -d stdout >$target
#%.ps:	%.gif mkfile
#	fb/gif2pic $stem.gif | fb/pic2ps -c >$stem.ps
#%.ps:	%.gif mkfile
#	lp -d stdout <$stem.gif >$stem.ps
%.pdf:	%.ps
	ps2pdf <$stem.ps >$stem.pdf
