<../../mkconfig

TARG=mk

OFILES=	arc.$O\
	archive.$O\
	bufblock.$O\
	env.$O\
	file.$O\
	graph.$O\
	job.$O\
	lex.$O\
	main.$O\
	match.$O\
	mk.$O\
	parse.$O\
	$TARGMODEL.$O\
	recipe.$O\
	rule.$O\
	run.$O\
	$TARGSHTYPE.$O\
	shprint.$O\
	symtab.$O\
	var.$O\
	varsub.$O\
	word.$O\

HFILES=	fns.h\
	../include/ar.h\
	mk.h\

LIBS=	regexp bio 9

BIN=$ROOT/$OBJDIR/bin

<$ROOT/mkfiles/mkone-$SHELLTYPE

CFLAGS=$CFLAGS -I../include

<mkfile-$HOSTMODEL
