<../mkconfig

LIB=libdraw.a

OFILES=	alloc.$O\
	allocimagemix.$O\
	arith.$O\
	bezier.$O\
	border.$O\
	buildfont.$O\
	bytesperline.$O\
	chan.$O\
	cloadimage.$O\
	computil.$O\
	creadimage.$O\
	defont.$O\
	draw.$O\
	drawrepl.$O\
	ellipse.$O\
	font.$O\
	freesubfont.$O\
	getdefont.$O\
	getsubfont.$O\
	init.$O\
	line.$O\
	mkfont.$O\
	openfont.$O\
	poly.$O\
	loadimage.$O\
	readcolmap.$O\
	readimage.$O\
	readsubfont.$O\
	rectclip.$O\
	replclipr.$O\
	rgb.$O\
	string.$O\
	stringbg.$O\
	stringsubfont.$O\
	stringwidth.$O\
	subfont.$O\
	subfontcache.$O\
	subfontname.$O\
	unloadimage.$O\
	window.$O\
	writecolmap.$O\
	writeimage.$O\
	writesubfont.$O\

HFILES=\
	$ROOT/include/draw.h \
	$ROOT/include/interp.h\

<$ROOT/mkfiles/mksyslib-$SHELLTYPE

