SYSTARG=NetBSD
OBJTYPE=386
<../../mkconfig
SYSTARG=NetBSD
OBJTYPE=386

#Configurable parameters

CONF=emu			#default configuration
CONFLIST=emu
CLEANCONFLIST=

INSTALLDIR=$ROOT/$SYSTARG/$OBJTYPE/bin	#path of directory where kernel is installed

#end configurable parameters

<$ROOT/mkfiles/mkfile-$SYSTARG-$OBJTYPE	#set vars based on target system

<| $SHELLNAME ../port/mkdevlist $CONF	#sets $IP, $DEVS, $PORT, $LIBS

OBJ=\
	asm-$OBJTYPE.$O\
	os.$O\
	$CONF.root.$O\
	lock.$O\
	$DEVS\
	$PORT\

HFILES=\

CFLAGS='-DROOT="'$ROOT'"' -DEMU -I. -I../port -I$ROOT/$SYSTARG/$OBJTYPE/include -I$ROOT/include -I$ROOT/libinterp $CTHREADFLAGS $CFLAGS $EMUOPTIONS
SYSLIBS= -lXext -lX11 -lossaudio -lm
KERNDATE=`{$NDATE}

default:V:	$O.$CONF

<../port/portmkfile

$O.$CONF:	$OBJ $CONF.c $CONF.root.h $LIBFILES
	$CC $CFLAGS '-DKERNDATE='$KERNDATE $CONF.c
	$LD $LDFLAGS -o $target $OBJ $CONF.$O $LIBFILES $SYSLIBS

install:V: $O.$CONF
	cp $O.$CONF $INSTALLDIR/$CONF

devfs.$O:	../port/devfs-posix.c
