SYSTARG=NetBSD
<../../mkconfig
SYSTARG=NetBSD

#Configurable parameters

CONF=emu			#default configuration
CONFLIST=emu
CLEANCONFLIST=

INSTALLDIR=$ROOT/$SYSTARG/$OBJTYPE/bin	#path of directory where kernel is installed

#end configurable parameters

# can remove or override X11LIBS using env section in config files
X11LIBS= -L/usr/X11R7/lib -R/usr/X11R7/lib -lXext -lX11

<$ROOT/mkfiles/mkfile-$SYSTARG-$OBJTYPE	#set vars based on target system

<| $SHELLNAME ../port/mkdevlist $CONF	#sets $IP, $DEVS, $PORT, $LIBS

OBJ=\
	asm-$OBJTYPE.$O\
	os.$O\
	segflush-$OBJTYPE.$O\
	kproc-pthreads.$O\
	$CONF.root.$O\
	lock.$O\
	$DEVS\
	$PORT\

HFILES=\

CFLAGS='-DROOT="'$ROOT'"' -DEMU -I. -I../port -I$ROOT/$SYSTARG/$OBJTYPE/include -I$ROOT/include -I$ROOT/libinterp $CTHREADFLAGS $CFLAGS $EMUOPTIONS
SYSLIBS= ${X11LIBS} -lossaudio -lm -lpthread
KERNDATE=`{$NDATE}

default:V:	$O.$CONF

$O.$CONF:	$OBJ $CONF.c $CONF.root.h $LIBFILES
	$CC $CFLAGS '-DKERNDATE='$KERNDATE $CONF.c
	$LD $LDFLAGS -o $target $OBJ $CONF.$O $LIBFILES $SYSLIBS
	$PAXCTL $target

install:V: $O.$CONF
	cp $O.$CONF $INSTALLDIR/$CONF

<../port/portmkfile

devfs.$O:	../port/devfs-posix.c
