# warning: autogenerated code; don't bother to change this, change mktypeset.b or abc.b instead
Abctypes: module {
	PATH: con "/dis/alphabet/abctypes.dis";
	Abccvt: adt {
		values: ref Extvalues->Values[ref Abc->Value];

		int2ext: fn(cvt: self ref Abccvt, v: ref Abc->Value): ref Alphabet->Value;
		ext2int: fn(cvt: self ref Abccvt, ev: ref Alphabet->Value): ref Abc->Value;
		dup: fn(cvt: self ref Abccvt, ev: ref Alphabet->Value): ref Alphabet->Value;
		free: fn(cvt: self ref Abccvt, ev: ref Alphabet->Value, used: int);
	};

	proxy: fn(): chan of ref Proxy->Typescmd[ref Alphabet->Value];
	proxy0: fn(): (
			chan of ref Proxy->Typescmd[ref Alphabet->Value],
			chan of (string, chan of ref Proxy->Typescmd[ref Abc->Value]),
			ref Abccvt
		);
};

Abcsubtypes: module {
	proxy: fn(): chan of ref Proxy->Typescmd[ref Abc->Value];
};
