<../../mkconfig

TARG=qc
OFILES=\
	cgen.$O\
	enam.$O\
	list.$O\
	machcap.$O\
	mul.$O\
	peep.$O\
	pgen.$O\
	pswt.$O\
	reg.$O\
	sgen.$O\
	swt.$O\
	txt.$O\

HFILES=\
	gc.h\
	q.out.h\
	../cc/cc.h\

LIBS=cc bio 9		# order is important

BIN=$ROOT/$OBJDIR/bin

<$ROOT/mkfiles/mkone-$SHELLTYPE

$ROOT/$OBJDIR/lib/libcc.a:
	cd ../cc
	mk $MKFLAGS install
	mk $MKFLAGS clean

%.$O: ../cc/%.c
	$CC $CFLAGS ../cc/$stem.c

#enam.c:	q.out.h
#	rc mkenam
