<../../mkconfig

TARG=8l

OFILES=\
	asm.$O\
	obj.$O\
	optab.$O\
	pass.$O\
	span.$O\
	list.$O\
	enam.$O\
	$TARGMODEL.$O\
	elf.$O\

HFILES=\
	l.h\
	../8c/8.out.h\
	../include/ar.h\

LIBS=bio 9			# order is important

BIN=$ROOT/$OBJDIR/bin

<$ROOT/mkfiles/mkone-$SHELLTYPE

CFLAGS=	$CFLAGS -I../include -I.

enam.$O:	../8c/enam.c
	$CC $CFLAGS ../8c/enam.c
elf.$O:	../ld/elf.c
	$CC $CFLAGS ../ld/elf.c

$TARGMODEL.$O:	../ld/$TARGMODEL.c
	$CC $CFLAGS ../ld/$TARGMODEL.c
