<../../mkconfig

TARG=\
	cssfont.dis\
	cssparser.dis\
	ebook.dis\
	mimeimage.dis\
	oebpackage.dis\
	reader.dis\
	strmap.dis\
	stylesheet.dis\
	table.dis\
	units.dis\

MODULES=\
	cssfont.m\
	cssparser.m\
	mimeimage.m\
	oebpackage.m\
	reader.m\
	strcache.m\
	strmap.m\
	stylesheet.m\
	units.m\
	table.m\

SYSMODULES=\
	css.m\
	draw.m\
	sys.m\
	tk.m\
	xml.m\

DISBIN=$ROOT/dis/ebook

<$ROOT/mkfiles/mkdis
