objtype=mips
OBJTYPE=$objtype
<../../mkconfig

LIB=libmp.a
SFILES=\
	mpvecadd.s\
	mpvecdigmuladd.s\
	mpvecdigmulsub.s\
	mpvecsub.s\
	mpdigdiv.s\

HFILES=$ROOT/Inferno/$OBJTYPE/include/u.h $ROOT/include/mp.h ../port/dat.h

OFILES=${SFILES:%.s=%.$O}

UPDATE=mkfile\
	$HFILES\
	$SFILES\

<$ROOT/mkfiles/mksyslib-$SHELLTYPE
