<../../../mkconfig

DIRS=\
	ppp\
#	nppp\

TARG=\
	bootpd.dis\
	dhcp.dis\
	ping.dis\
	rip.dis\
	tftpd.dis\
	virgild.dis\
	sntp.dis\

SYSMODULES=\
	attrdb.m\
	bufio.m\
	dhcp.m\
	draw.m\
	ether.m\
	ip.m\
	ipattr.m\
	sys.m\

DISBIN=$ROOT/dis/ip

<$ROOT/mkfiles/mkdis
<$ROOT/mkfiles/mksubdirs
